name: flutter_architecture
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  mobx: 0.4.0
  flutter_mobx: 0.3.6

  provider: ^4.0.1

  fluro: 1.5.0

  dio: ^3.0.8

  flutter_secure_storage: ^3.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen: ^0.4.0+1

  test:
  # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/res/strings/
    - lib/res/images/
    #    - somin-influencer-response.json
  fonts:
    - family: Lato
      fonts:
      - asset: lib/res/fonts/Lato-Regular.ttf
      - asset: lib/res/fonts/Lato-Italic.ttf
        style: italic
      - asset: lib/res/fonts/Lato-Hairline.ttf
        weight: 100
      - asset: lib/res/fonts/Lato-HairlineItalic.ttf
        weight: 100
        style: italic
      - asset: lib/res/fonts/Lato-Thin.ttf
        weight: 200
      - asset: lib/res/fonts/Lato-ThinItalic.ttf
        weight: 200
        style: italic
      - asset: lib/res/fonts/Lato-Light.ttf
        weight: 300
      - asset: lib/res/fonts/Lato-LightItalic.ttf
        weight: 300
        style: italic
      - asset: lib/res/fonts/Lato-Medium.ttf
        weight: 500
      - asset: lib/res/fonts/Lato-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: lib/res/fonts/Lato-Semibold.ttf
        weight: 600
      - asset: lib/res/fonts/Lato-SemiboldItalic.ttf
        weight: 600
        style: italic
      - asset: lib/res/fonts/Lato-Bold.ttf
        weight: 700
      - asset: lib/res/fonts/Lato-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: lib/res/fonts/Lato-Heavy.ttf
        weight: 800
      - asset: lib/res/fonts/Lato-HeavyItalic.ttf
        weight: 800
        style: italic
      - asset: lib/res/fonts/Lato-Black.ttf
        weight: 900
      - asset: lib/res/fonts/Lato-BlackItalic.ttf
        weight: 900
        style: italic
